import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeHOC } from "../frontend/wrappers/themeHOC";
import { Navbar } from "@/frontend/components/layout/navbar/navbar";
import { AuthWrapper } from "../frontend/wrappers/AuthWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthWrapper>
          <ThemeHOC>
            <Navbar />
            <main>{children}</main>
          </ThemeHOC>
        </AuthWrapper>
      </body>
    </html>
  );
}
